compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

packageExtensions:
  "@octokit/plugin-retry@4.1.6":
    dependencies:
      "@octokit/request-error": 3.0.3

plugins:
  - checksum: e1dfe924b047de2dadde61d71c586d1dda79e9ef5277aad39f44abfc71b56028d5eea0f858348d4c1ac3ef54399010f9f0907fbe9fa3420fbf620a3733e3ea97
    path: .yarn/plugins/@yarn.build/plugin-all.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
