name: Dependency Pull Request

on:
  pull_request:
    branches: [master]
    paths:
      - '**/package.json'

jobs:
  check-cache:
    name: Check Yarn Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Check dependencies
        run: yarn --check-cache
      - uses: EndBug/add-and-commit@v7
        with:
          add: .yarn .pnp.js yarn.lock
          default_author: github_actions
          message: 'chore(package): update dependencies'

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [check-cache]
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
